name: Build and Release

on:
  push:
    branches:
      - main
    paths:
      - '.env'
  workflow_dispatch:  # This enables manual triggering via the GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .env file for APP_VERSION
      run: |
        # Load environment variables from the .env file
        echo "Loading .env"
        cat .env

    - name: Build the tar.gz file
      run: |
        # Ensure APP_VERSION exists
        if [[ -z "${APP_VERSION}" ]]; then
          echo "APP_VERSION is not set!"
          exit 1
        fi
        # Build the name for the tar.gz file
        tar_name="${APP_NAME}_v${APP_VERSION}.tar.gz"
        just build

    - name: Create a GitHub release
      uses: softprops/action-gh-release@v1
      with:
        files: ./${tar_name}

    - name: Clean up
      run: |
        # Clean up temporary files if necessary
        echo "Cleaning up..."
